os:
  - linux
  - osx
language: rust
rust:
  - stable
env: ZOHO_PORTAL_NAME=notarealportal ZOHO_PROJECT_NAME=notarealproject
script:
  - cargo test
  - cargo build --release
  - strip target/release/release_bot
before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mv target/release/release_bot release_bot-$(git describe --tags)-Darwin-x86-64 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mv target/release/release_bot release_bot-$(git describe --tags)-Linux-x86-64 ; fi
deploy:
  provider: releases
  api_key:
    secure: Q5fWZT4QOjNq529yRPLGXSOVLgTSGJGkLeoIJIAAsxleBW4wNdqWVNXb0RgFAujJtvgiT6HkSpr5nbj6MiKCDXbVyyJPL6WW6HCyJgN/MEk07QqsymdBST7QMfblmGekvbVys6B4X+UIKu9lsbWDV9sOvtzZ1fhwWyfu7n1T0dAxnEP0mwLeeuvuEQI86JQD164zQd3uWWSUUss8l0vgKXrFc36imbrgjC0iM5Y7ku53dpbTwtm2XaLTJwZkYdVQ6ZDFw/aef9IEyCxRlCctb2lLcIQLoC0IX+TkEGIkg/WE8irSBHCb0C9w4EijMnevH8ubMfLYrIax6v8RXqMP58ei9B6Ktr5Gjauncl25v7impInFMujE7KBvTfO+MNpzQHZVNLetsX9D4cbTkTzChGAtZsgeViFeU+jk4br0UCfwbKlmieHWOKRaLhva24BcShk5yp3rOwS4V3YHX+bpugX3HOBfbqwTE4BLHpyun1DEqnrP3mhPBdSLkEtMUZ+v/L3yGaRnYSOC3/LwAo5y3okV79X+z9xMU8EM1KFlbCdZpa4ZgVyaEnKZesc1drogAFVh41Y4jKQzpqjtaPyVbRPKNfEoTeH2omqDzX/cONI7hE8nip2I8QH0DKU/633pE8k+ZdRUplpjpRpllgi3RMF/yjHrb6kNR+NXeiHHhBs=
  file:
    - release_bot-$(git describe --tags)-Darwin-x86-64
    - release_bot-$(git describe --tags)-Linux-x86-64
  name: Release Bot $(git describe --tags)
  body: $(git show -s --format=%B HEAD)
  prerelease: true
  skip_cleanup: true
  on:
    repo: Xymist/release_bot
    tags: true
