[package]
name = "release_bot"
version = "0.4.0"
authors = ["Xymist <james@jamieduerden.me>"]
readme = "README.md"

[dependencies]
clap = "2.26"
dotenv = "0.10"
error-chain = "0.11"
hyper = "0.11"
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0"
regex = "0.2"
lazy_static = "0.2.9"
Inflector = "0.11.0"
clippy = {version = "*", optional = true}
toml = "0.4"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[features]
default = ["clippy"]